LRQA-82628
MathausC/liferay-portal pull request #14
Opened 2023-09-01 13:49 UTC by rubenssoares-br

2023-09-01 13:49 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-01 13:50 UTC, rubenssoares-br commented
ci:test:sf

2023-09-01 13:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/5687/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5687/jenkins-report.html">here</a>.</b></p>

2023-09-01 13:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cfdd0b8eb237264fa2825d0148d02edc305dc5a1">cfdd0b8eb237264fa2825d0148d02edc305dc5a1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rubenssoares-br/liferay-portal/tree/LRQA-82628">LRQA-82628</a><br/>Branch GIT ID: <a href="https://github.com/rubenssoares-br/liferay-portal/commit/90c1d1660ebb8f630dc4326f9d662046efeb82bf">90c1d1660ebb8f630dc4326f9d662046efeb82bf</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/5687/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5687/jenkins-report.html">here</a>.</h5></details></html>

2023-09-01 13:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/5687/">test-portal-source-format#5687</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5687/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/MathausC/liferay-portal/pull/14">MathausC#14</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2417401013">[master] ci:test:sf - rubenssoares-br &gt; MathausC - PR#14 - 2023-09-01[06:50:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/21676/">publish-testray-report#21676</a><br/></div></div>

2023-09-04 20:06 UTC, MathausC requested changes

2023-09-04 20:06 UTC, MathausC commented on portal-web/test/functional/com/liferay/portalweb/tests/MyBlogTests/MyBlogTests.testcase
> +	@description = "Can Create a Blog"
A descricao precisa ser atualizada.

2023-09-04 20:06 UTC, MathausC commented on portal-web/test/functional/com/liferay/portalweb/tests/MyBlogTests/MyBlogTests.testcase
> +	}
Tu pode mandar esses testes no mesmo arquivos que os outros testes, assim como ta no Slide 22. Assim tu vai poder praticar criar testes no mesmo arquivo que nao impactao entre si.

2023-09-05 13:17 UTC, rubenssoares-br commented
Teste adicionado a outros testes do Blogs no testcase do PR - https://github.com/MathausC/liferay-portal/pull/17

2023-09-05 13:17 UTC, closed without merging