LRQA-82629
MathausC/liferay-portal pull request #15
Opened 2023-09-01 15:48 UTC by rubenssoares-br

2023-09-01 15:48 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-01 15:51 UTC, rubenssoares-br commented
ci:test:sf

2023-09-01 15:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/2220/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2220/jenkins-report.html">here</a>.</b></p>

2023-09-01 15:56 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cfdd0b8eb237264fa2825d0148d02edc305dc5a1">cfdd0b8eb237264fa2825d0148d02edc305dc5a1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rubenssoares-br/liferay-portal/tree/LRQA-82629">LRQA-82629</a><br/>Branch GIT ID: <a href="https://github.com/rubenssoares-br/liferay-portal/commit/00bd24c7ad781c7c3bbba7d08d348d2b2be1c0e5">00bd24c7ad781c7c3bbba7d08d348d2b2be1c0e5</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2220/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2220/jenkins-report.html">here</a>.</h5></details></html>

2023-09-01 15:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2220/">test-portal-source-format#2220</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2220/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/MathausC/liferay-portal/pull/15">MathausC#15</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2417432576">[master] ci:test:sf - rubenssoares-br &gt; MathausC - PR#15 - 2023-09-01[08:52:02]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/9456/">publish-testray-report#9456</a><br/></div></div>

2023-09-01 17:19 UTC, rubenssoares-br commented on portal-web/test/functional/com/liferay/portalweb/tests/MyBlogTests/MyBlogTests.testcase
> +				entryTitle = "2 Blogs SDG T");
@MathausC sabe dizer se teria alguma outra macro que fizesse o "Assert" fora essa: `BlogsEntry.viewPG`? Pois pelo oq eu vi na path dela, ela utiliza o `contains` em seu XPATH, entao caso o Title e Content da minha segunda Entry fosse "Blogs SDG Title 2" Daria erro, pois ela encontraria 2 title e 2 content, quando fosse dar o Assert da primeira Entry que eh "Blogs SDG Title", por exemplo. Nesse caso de teste, funcionou pq eu alterei os nomes, mas so por curiosidade gostaria de saber se tem alguma outra.

2023-09-04 20:17 UTC, MathausC commented on portal-web/test/functional/com/liferay/portalweb/tests/MyBlogTests/MyBlogTests.testcase
> +				entryTitle = "2 Blogs SDG T");
Eu acho que nao exista outra, mas tu fez o correto em criar nomes diferentes pra as duas. Pra ser mais acertivo eu faria nomes completamente diferentes, pra garantir a eficacia do teste.

2023-09-04 20:19 UTC, MathausC requested changes

2023-09-04 20:19 UTC, MathausC commented on portal-web/test/functional/com/liferay/portalweb/tests/MyBlogTests/MyBlogTests.testcase
> +	@description = "Can Create a Blog"
atualizar a descricao.

2023-09-04 20:19 UTC, MathausC commented on portal-web/test/functional/com/liferay/portalweb/tests/MyBlogTests/MyBlogTests.testcase
> +	}
Tenta colocar junto com os outros testes. E ainda mais, tu poderia colocar todos no mesmo PR.

2023-09-05 13:18 UTC, rubenssoares-br commented
Teste adicionado a outros testes do Blogs no testcase do PR - https://github.com/MathausC/liferay-portal/pull/17

2023-09-05 13:18 UTC, closed without merging