LRQA-82630
MathausC/liferay-portal pull request #16
Opened 2023-09-01 18:09 UTC by rubenssoares-br

2023-09-01 18:10 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-01 18:10 UTC, rubenssoares-br commented
ci:test:sf

2023-09-01 18:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/1480/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1480/jenkins-report.html">here</a>.</b></p>

2023-09-01 18:14 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cfdd0b8eb237264fa2825d0148d02edc305dc5a1">cfdd0b8eb237264fa2825d0148d02edc305dc5a1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rubenssoares-br/liferay-portal/tree/LRQA-82630">LRQA-82630</a><br/>Branch GIT ID: <a href="https://github.com/rubenssoares-br/liferay-portal/commit/6c71b47b28bc6fe96193e85ed937679572fbf749">6c71b47b28bc6fe96193e85ed937679572fbf749</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1480/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1480/jenkins-report.html">here</a>.</h5></details></html>

2023-09-01 18:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1480/">test-portal-source-format#1480</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1480/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/MathausC/liferay-portal/pull/16">MathausC#16</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2417575572">[master] ci:test:sf - rubenssoares-br &gt; MathausC - PR#16 - 2023-09-01[11:10:53]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/5946/">publish-testray-report#5946</a><br/></div></div>

2023-09-04 20:24 UTC, MathausC requested changes

2023-09-04 20:24 UTC, MathausC commented on portal-web/test/functional/com/liferay/portalweb/tests/MyBlogTests/MyBlogTests.testcase
> +				entryTitle = "2 Blogs SDG T");
Como esse teste eh para pesquisar os blogs, nao precisa fazer o assert aqui. Somente a criacao.

2023-09-04 20:24 UTC, MathausC commented on portal-web/test/functional/com/liferay/portalweb/tests/MyBlogTests/MyBlogTests.testcase
> +	}
Seria bom os testes de blogs estatem no mesmo arquivo.

2023-09-05 13:18 UTC, rubenssoares-br commented
Teste adicionado a outros testes do Blogs no testcase do PR - https://github.com/MathausC/liferay-portal/pull/17

2023-09-05 13:18 UTC, closed without merging