LRQA-82631
MathausC/liferay-portal pull request #18
Opened 2023-09-06 16:05 UTC by rubenssoares-br

2023-09-06 16:05 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-06 16:15 UTC, rubenssoares-br commented
ci:test:sf

2023-09-06 16:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-17.liferay.com/job/test-portal-source-format/6453/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6453/jenkins-report.html">here</a>.</b></p>

2023-09-06 16:21 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5ea8d94b4f584daf31904e84275d932bdacabee9">5ea8d94b4f584daf31904e84275d932bdacabee9</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rubenssoares-br/liferay-portal/tree/LRQA-82631">LRQA-82631</a><br/>Branch GIT ID: <a href="https://github.com/rubenssoares-br/liferay-portal/commit/dd6747c892ec9c6bc683d1fcb3a26a8ccfa87c11">dd6747c892ec9c6bc683d1fcb3a26a8ccfa87c11</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-source-format/6453/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6453/jenkins-report.html">here</a>.</h5></details></html>

2023-09-06 16:34 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-17.liferay.com/job/test-portal-source-format/6453/">test-portal-source-format#6453</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6453/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/MathausC/liferay-portal/pull/18">MathausC#18</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2419714521">[master] ci:test:sf - rubenssoares-br &gt; MathausC - PR#18 - 2023-09-06[09:16:21]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-17.liferay.com/job/publish-testray-report/3428/">publish-testray-report#3428</a><br/></div></div>

2023-09-06 16:52 UTC, rubenssoares-br commented
ci:test:relevant

2023-09-06 17:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/1923/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1923/jenkins-report.html">here</a>.</b></p>

2023-09-08 19:02 UTC, MathausC requested changes

2023-09-08 19:02 UTC, MathausC commented on portal-web/test/functional/com/liferay/portalweb/tests/MyDMTests/MyDMTests.testcase
> +	test CanCreateDM {
Eu sei que o Given esta implicito no SetUp, mas nao existiria nenhuma maneira dele estar no teste?

2023-09-08 19:02 UTC, MathausC commented on portal-web/test/functional/com/liferay/portalweb/tests/MyDMTests/MyDMTests.testcase
> +		}
Esse poderia ser o Given.

2023-09-08 19:02 UTC, MathausC commented on portal-web/test/functional/com/liferay/portalweb/tests/MyDMTests/MyDMTests.testcase
> +		}
Bom verificar a presenca do DMTest 2, mas falta verificar a ausencia do DMtest 1.

2023-09-08 19:02 UTC, MathausC commented on portal-web/test/functional/com/liferay/portalweb/tests/MyDMTests/MyDMTests.testcase
> +		}
Esse poderia ser o Given do teste.

2023-09-08 19:02 UTC, MathausC commented on portal-web/test/functional/com/liferay/portalweb/tests/MyDMTests/MyDMTests.testcase
> +		}
Este poderia ser o Given do teste.

2023-09-08 19:02 UTC, MathausC commented on portal-web/test/functional/com/liferay/portalweb/tests/MyDMTests/MyDMTests.testcase
> +		}
Seria legal ter mais um DM no teste que tu verificasse que nao mudou junto com a edicao do outro DM, para verificar que a edicao so afeta o DM alvo.

2023-09-11 13:12 UTC, MathausC commented
Excelente trabalho, @rubenssoares-br. Meus parabens!

2023-09-11 13:26 UTC, rubenssoares-br commented
ci:test:sf

2023-09-11 13:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-18.liferay.com/job/test-portal-source-format/7119/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7119/jenkins-report.html">here</a>.</b></p>

2023-09-11 13:35 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d7210e871573904fcf486a55af02f57f5a2d2c74">d7210e871573904fcf486a55af02f57f5a2d2c74</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rubenssoares-br/liferay-portal/tree/LRQA-82631">LRQA-82631</a><br/>Branch GIT ID: <a href="https://github.com/rubenssoares-br/liferay-portal/commit/145963aadbf20a47182c47dc22a8a5c6d750efe1">145963aadbf20a47182c47dc22a8a5c6d750efe1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-source-format/7119/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7119/jenkins-report.html">here</a>.</h5></details></html>

2023-09-11 13:40 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-18.liferay.com/job/test-portal-source-format/7119/">test-portal-source-format#7119</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7119/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/MathausC/liferay-portal/pull/18">MathausC#18</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2422091178">[master] ci:test:sf - rubenssoares-br &gt; MathausC - PR#18 - 2023-09-11[06:27:17]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-18.liferay.com/job/publish-testray-report/4367/">publish-testray-report#4367</a><br/></div></div>

2023-09-11 13:46 UTC, rubenssoares-br commented
ci:test:relevant

2023-09-11 14:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/8934/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8934/jenkins-report.html">here</a>.</b></p>

2023-09-11 14:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/8934/">test-portal-acceptance-pullrequest(master)#8934</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8934/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/MathausC/liferay-portal/pull/18">MathausC#18</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2422145191">[master] ci:test:relevant - rubenssoares-br &gt; MathausC - PR#18 - 2023-09-11[07:43:19]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/18326/">publish-testray-report#18326</a><br/></div></div>

2023-09-11 15:23 UTC, closed without merging